/**
 * @file util_asm.S
 * @brief Implémentation utilitaires (assembleur)
 * @author Copyright © 2011-2012 epsilonRT. All rights reserved.
 * @copyright GNU Lesser General Public License version 3
 *            <http://www.gnu.org/licenses/lgpl.html>
 * @version $Id$
 * Revision History ---
 *    20111113 - Initial version by epsilonRT
 */
#include "util_rand8.S"
#include "util_swapbytes.S"

/* ========================================================================== */

